---
title: "R Notebook"
output: html_notebook
---


```{r, message=FALSE}
library(knitr)
library(rmarkdown)
library(tidyverse)
library(lubridate)
library(pander)
library(NLP)
library(tm)
library(rlist)
library(quantmod) # Financial library
library(data.table)
library(dtplyr)
# library(treemap)
# library(plot3D)
# library(plot3Drgl)
rm(list = ls())
```

```{r}

# source("code_01_functions.R")
source("code_00_functions.R")
source("code_01_functions.R")
#### ------------------------------------------------------------------------
#
# get all of the energy stock symbols
symbols <- f1_get_company_stock_names(keep_sector = "Energy")
# we have too many stocks, and not enough money, so restrict the stocks
symbols <- head(symbols, n = 20)
symbols
```

```{r}
#### ------------------------------------------------------------------------
#
# Uncomment to get the stock data from the yahoo server for the given time span
 #  stocks_data <- f2_get_stock_data(symbols, from = mdy("1-1-2010"), to = mdy("1-1-2012") )

# Uncomment to save the newly fetched stock data to file
  #  saveRDS(stocks_data, file = "./data/stocks_data.rds")

# read the saved stock data from file
stocks_data <- readRDS( file = "./data/stocks_data.rds")
stocks_data[[1]][1:5]
```

```{r}

#### ------------------------------------------------------------------------
#
#' convert the stocks to a data frame, rename the columns, flatten and nest
by_stock <- f3_flatten_and_nest_by_stock(dl = stocks_data)
by_stock
by_stock %>% unnest(data)
```

```{r}
#### ------------------------------------------------------------------------
#
# we have 2 years of data. I am going to cut it up into 12 time slices
by_window_stock <- f5_get_rsi_and_slice_into_windows(slices = 24, by = by_stock)
by_window_stock
by_window_stock %>% unnest()

# what constitutes an interesting stock? does the stock have to pass thru an 'rsi' of
# 50 to be interesting? I am defining it as for a particular time window, which stock's
# RSI swings more then 50?
interesting_stocks <- by_window_stock %>% unnest %>%
  filter(window ==1) %>%
  group_by(stock) %>%
  filter(max(rsi) - min(rsi) > 50)

interesting_stocks

by_interesting_stocks <- interesting_stocks %>% group_by(stock) %>% nest()
by_interesting_stocks
```
```{r}

#### ------------------------------------------------------------------------
# Create a grid of scenario arguments so we can find the max roi
args <- f6_create_grid_of_arguments()
args[1,]
args
```

```{r}
#### ------------------------------------------------------------------------
# unnest a window of data
data <- by_interesting_stocks %>% unnest()
#data <- by_window_stock %>% filter(window == 1) %>% unnest(data)
data
```

```{r}
# group by date, then order by date and rsi
data  %>% group_by(date) %>% arrange(date, desc(rsi)) 
```

```{r}
#### ------------------------------------------------------------------------
run_simulation <- function(by_window = by_window_stock, buy = 40, 
                           sell = 55, percent = .3, cash_on_hand = 2000){
  # by_window    <- by_window_stock
  #  by_window    <- by_interesting_stocks
  # buy          <- 40
  # sell         <- 70
  # percent      <- .2
  # cash_on_hand <- 1000
  # 
  
  # unnest and filter a window of data (filter for testing purposes)
  dl <- by_window %>%
    
   # filter(window < 2, stock == "CRZO" | stock == "MMLP") %>%
    unnest() %>%
    filter(window < 4) %>% 
    # filter(date < ymd("2010-03-15")) %>%
    group_by(date) %>% arrange(date, desc(rsi))

  # depending on the rsi, set the transaction to buy/sell or hold
  dl$transaction[dl$rsi > sell] <- "sell"
  dl$transaction[dl$rsi < buy]  <- "buy"
  
  
  # setup up a log_book for our current holdings
  log_book <- dl %>%
    
    select(date, stock, shares, amount, roi) %>%
    group_by(stock) %>%
    summarise(shares = sum(shares),
              amount = last(amount),
              roi    = last(roi)) %>%
  
    # turn our log_book into a 'data.table'
    tbl_dt() %>%
    
    # make the stock column a 'key'
    setkey(stock) 
  
  # log_book["CLMT", shares := 50]  
  
  for (i in 1:nrow(dl)) {
      # i = 1

    # do we buy anything today?
    price_of_stock          <- dl$close[i]
    proceeds_from_sale      <- 0
    shares_sold             <- 0
    transaction             <- dl$transaction[i]
    stock_name              <- dl$stock[i]
    shares_i_own            <- log_book[dl$stock[i], shares]
    
    # calculate the shares I want to sell
    shares_i_want_to_sell   <- trunc(percent*shares_i_own)
      
    if ( transaction == "sell"  ) {
 
      # update the dl$shares and shares owned logbook 
      dl$shares[i] <- -shares_i_want_to_sell
      log_book[stock_name, shares := shares_i_own - shares_i_want_to_sell]
      
      # calculate cash gained from stock sold
      proceeds_from_sale <- shares_i_want_to_sell * price_of_stock
      
      # update cash balance and record the sale in the dl
      cash_on_hand       <- cash_on_hand + proceeds_from_sale
      dl$balance[i]      <- cash_on_hand
      dl$amount[i]       <- proceeds_from_sale
    }
    
    # calculate the shares I want to buy
    shares_i_want_to_buy    <- trunc(percent*cash_on_hand/price_of_stock)
    
    # calculate the cash I would spend buying the stock
     cost_of_stock <- shares_i_want_to_buy * price_of_stock

    if ( transaction == "buy" && cash_on_hand >= cost_of_stock ) {
      
    # update the dl$shares and shares owned logbook
     dl$shares[i] <- shares_i_want_to_buy
     log_book[stock_name, shares := shares_i_own + shares_i_want_to_buy]
     
     # update cash balance and record the sale in the dl
     cash_on_hand  <-  cash_on_hand - cost_of_stock
     dl$amount[i]  <- -cost_of_stock
     dl$balance[i] <- cash_on_hand
     log_book[stock_name, amount := amount + cost_of_stock]
    }
     
    if ( transaction == "hold"  ) {
      
     # update cash balance 
     dl$balance[i] <- cash_on_hand
     
    }
     # update the roi return on investment
     # calculate the roi = shares we own * todays closing price / amount spent
     log_book[stock_name, roi := shares * dl$close[i] / log_book[stock_name, amount]]
     # store the roi in the daily table
     dl$roi[i] <- log_book[stock_name, roi]
  }
    # calculate roi return on investment???
    # dl2 <- dl %>%
    #   group_by(stock) %>%
    #   summarise(roi2 = sum(shares * last(close))/sum(amount))
     
  return(list(dl, log_book))
}

# sim_results <- run_simulation(by_window = by_window_stock, buy = 29, sell = 50, percent = .1, 
#                               cash_on_hand = 5000)
sim_results <- run_simulation(by_window = by_interesting_stocks, buy = 29, sell = 50, percent = .1, 
                              cash_on_hand = 5000)


sim_results[1]
sim_results[2] 
sim_results[3]
  # 

```

```{r}
#### ------------------------------------------------------------------------

results_by_stock <- sim_results[1] %>%
  as.data.frame %>% group_by(stock) %>%
  nest()

sim_results[1] %>% as.data.frame() %>%
  ggplot(aes(x = date, y = roi, color = stock)) + geom_line()


buy_sell <- sim_results[1] %>% as.data.frame %>% ungroup 
buy_sell



my_stocks <- sim_results[2] %>% as.data.frame
my_stocks
glimpse(buy_sell)
sim_results[3]
```

